config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
 

  resources :users do
  	resources :articles
  	resources :comments
  end

  resources :articles do
  	resources :comments
  end

  root 'static_pages#index'

  get 'static_pages/index'

  get 'static_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:    
    user ||= User.new # guest user (not logged in)
        can :manage, :all if user.role == "admin"
        can :read, :all
        can :manage, User, id: user.id
        can :manage, Comment, id: user.id
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	self.per_page = 3

	has_many :comments, dependent: :destroy
	belongs_to :user, optional: true
	validates :title, presence: true,
                    length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  self.per_page = 3
  
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
  validates :user, presence: true
  validates :article, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :articles
	has_many :comments

	ROLES = %w[admin moderator author banned].freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
		@articles = Article.paginate(:page => params[:page])
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
  	@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
 
 	  if @article.save
  		redirect_to @article
  	else
  		render 'new'
  	end	
	end

	def update
		@article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
	end

	def destroy
  	@article = Article.find(params[:id])
  	@article.destroy
 
  	redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :prepare_article
  before_action :authenticate_user!, :except => [:show, :index]

  def index
    @comment = Comment.paginate(page: params[:page])
  end

	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end

  def prepare_article
    @article = Article.find(params[:article_id])  
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
  # POST /users
  # POST /users.json
  def create
    @user = User.new(users_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_later
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid article_index">
  <div class="row">
    <header><h1>Articles</h1></header>
    <div class="col-md-12">
      <% @articles.each do |article| %>
        <h3><%= article.title %></h3>
        <p><%= simple_format(article.text) %></p>
        <%= link_to 'Show', article_path(article) %>
        <% if signed_in? %>
           | <%= link_to 'Edit', edit_article_path(article) %> | <%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  </div>  
</div>
<%= will_paginate @acticles %>

app/views/articles/new.html.erb
<% if not signed_in? %>
  <p>You need to be signed in to write an article.</p>
<% end %>
<% if signed_in? %>

<h1>New Article</h1>

<%= render 'form' %>
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="container-fluid show-article">
	<div class="row">
		<p><strong><%= @article.title %></strong></p>
 		<p><%= simple_format(@article.text) %></p>
	</div>
	<div class="row">
		<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
			<% if not signed_in? %>
		<p>You need to be signed in to leave a comment.</p>
	<% end %>
	<% if signed_in? %>
		<h4>Add a comment:</h4>
		<%= render 'comments/form' %>
	<% end %>
	</div>
	<% if signed_in? %>
		<%= link_to 'Edit', edit_article_path(@article) %> |
	<% end %>
	<%= link_to 'Back', articles_path %>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :body, "Comment" %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A fake blog
    by <a href="https://www.bitballoon.com/sites/dutchkdesign">Kim van Dijk</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="ida navbar-brand">
        <%= link_to "blog", static_pages_index_path, id: "logo" %>
      </div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'New article', new_article_path %></li>
        <li role="search" id="search">
          <%= form_tag(articles_path, method: "get", class: "row") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag "Search", name: nil %>
          <% end %>
        </li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <% if user_signed_in? %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
            <li><%= link_to('Sign in', new_user_session_path) %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <% if notice %>
  <p id="notice" class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= notice %></p>
  <% end %>
   
  <% if alert %>
  <p id="alert" class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= alert %></p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="container">
      <%= yield %>
      <div id="spacer"></div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<table>
  <tbody>
    <tr>
      <td><h2>Welcome!</h2></td>
    </tr>
    <tr>
      <td><p>Thank you for signing up with <%= @appname %>!</p></td>
    </tr>
    <tr>
      <td><p><strong>Your <%= @appname %> Team!</strong></p></td>
    </tr>
  </tbody>
</table>

app/views/static_pages/contact.html.erb
<body id="contact_page">
	<div class="container-fluid" id="contact" >
  	<div class="header">
  	<h1>Contact us</h1>
  	<h3>If you have a question for us about our products or if you want to make a special order let us know!</h3>
  	</div><!-- end header -->
  	<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do %>
<div class="row">
	<div class=""col-md-4>
		<div class="form-group">
			<%= label_tag :name, "Name *" %>
			<%= text_field_tag :name, nil, class: "form-control", :required => true, placeholder: "Enter Name" %>
		</div> 
		<div class="form-group">
			<%= label_tag :phone, "Phone number *" %>
			<%= text_field_tag :phone, nil, class: "form-control", :required => true, placeholder: "Enter Phone number" %>
		</div>     
		<div class="form-group">
			<%= label_tag :email, "Email Address *" %>
			<%= text_field_tag :email, nil, class: "form-control", :required => true, placeholder: "Enter Email" %>
		</div>
		<div class="form-group">
			<%= label_tag :message, "Your message below. *" %>
			<%= text_area_tag :message, nil, class: "form-control", style: "resize:none", cols: "40", rows: "5", :required => true, placeholder: "Enter Message" %>
			<p id="char-count"></p><p id="visible-comment"></p>
		</div>
	</div>  
</div>	
<%= submit_tag("Send", class: "btn btn-default") %>  
<% end %>

	</div>
</body>

app/views/static_pages/index.html.erb
<div class="container" id="welcome">
	<h1>Welcome to this blog for show!</h1>
	<%= link_to ' See the articles ', controller: 'articles' %>
	<%= link_to ' Create a new article ', new_article_path %>
	<br>
	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>

	<%= link_to image_tag("mac_marble_pink_gold.jpg", alt: "Macbook girly", class: "img-responsive")%>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= f.collection_select :role, User::ROLES, :to_s, :humanize %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th> First name | </th>
      <th> Last name | </th>
      <th> Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= link_to "Sign up", new_user_registration_path %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>